apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: cert-volume
          secret:
            secretName: "secret-nginx-cert" 
      containers:
      - name: nginx
        image: vudinhquang/swarmtest:nginx
        imagePullPolicy: "Always"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - mountPath: "/certs"
            name: cert-volume 
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
  type: NodePort
  ports:
  - port: 8080        # cong dich vu anh xa vao cong POD
    targetPort: 80    # cong POD anh xa vao container
    protocol: TCP
    name: http
    nodePort: 31080   # cong NODE anh xa vao cong dich vu (chi chon 30000-32767)

  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
    nodePort: 31443
  # Chu y it is same to Label cua POD tai Deployment
  selector:
    app: nginx