apiVersion: v1
kind: Pod
metadata:
  name: nginx-swarmtest-vol
  labels:
    app: myapp
spec:
  nodeSelector:
    hostname: worker1.xtl
  volumes:
    # Dinh nghia mot volume - anh xa thu muc /home/www may host
    - name: "myvol"
      hostPath:
        path: "/home/html"
  containers:
  - name: n1
    image: nginx:1.17.6
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: "myvol"
  - name: s1
    image: vudinhquang/swarmtest:node
    resources:
      limits:
        memory: "150Mi"
        cpu: "100m"
    ports:
      - containerPort: 8085
    volumeMounts:
      - mountPath: /data/
        name: "myvol"