apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rsapp-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: rsapp
  minReplicas: 5
  maxReplicas: 10
  # Thuc hien scale CPU hoat dong o 50% so voi CPU ma POD yeu cau
  targetCPUUtilizationPercentage: 50